# Generated by Django 4.0.3 on 2022-12-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=100)),
                ('contact_name_1', models.CharField(max_length=30)),
                ('contact_phone_1', models.IntegerField()),
                ('contact_email_1', models.EmailField(max_length=254)),
                ('contact_name_2', models.CharField(max_length=30)),
                ('contact_phone_2', models.BigIntegerField()),
                ('contact_email_2', models.EmailField(max_length=254)),
                ('contact_name_3', models.CharField(max_length=30)),
                ('contact_phone_3', models.BigIntegerField()),
                ('contact_email_3', models.EmailField(max_length=254)),
                ('work_order_valid', models.DateField()),
                ('scope', models.CharField(max_length=30)),
            ],
        ),
    ]
