# Generated by Django 4.0.3 on 2022-12-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_rename_client_name_cloud_client name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloud',
            old_name='Client Name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='cloud',
            old_name='Contact email 1',
            new_name='contact_email_1',
        ),
        migrations.RenameField(
            model_name='cloud',
            old_name='Contact email 2',
            new_name='contact_email_2',
        ),
        migrations.RenameField(
            model_name='cloud',
            old_name='Contact email 3',
            new_name='contact_email_3',
        ),
        migrations.RenameField(
            model_name='cloud',
            old_name='Contact name 1',
            new_name='contact_name_1',
        ),
        migrations.RenameField(
            model_name='cloud',
            old_name='Contact name 2',
            new_name='contact_name_2',
        ),
        migrations.RenameField(
            model_name='cloud',
            old_name='Contact name 3',
            new_name='contact_name_3',
        ),
        migrations.RenameField(
            model_name='cloud',
            old_name='Contact phone 1',
            new_name='contact_phone_1',
        ),
        migrations.RenameField(
            model_name='cloud',
            old_name='Contact phone 2',
            new_name='contact_phone_2',
        ),
        migrations.RenameField(
            model_name='cloud',
            old_name='Contact phone 3',
            new_name='contact_phone_3',
        ),
        migrations.RenameField(
            model_name='cloud',
            old_name='Project ID',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='cloud',
            old_name='Name of project',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='cloud',
            old_name='Scope of work',
            new_name='scope',
        ),
        migrations.RenameField(
            model_name='cloud',
            old_name='Work order valid till',
            new_name='work_order_valid',
        ),
    ]
