# Generated by Django 4.0.3 on 2022-12-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_vmrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.IntegerField()),
                ('dept_name', models.CharField(max_length=30)),
                ('no_of_vm', models.IntegerField(default=1)),
                ('ram', models.IntegerField()),
                ('vcpu', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('operating_system', models.CharField(max_length=20)),
            ],
        ),
    ]
