# Generated by Django 4.0.3 on 2022-12-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_vmreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalServerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=30)),
                ('server_make_model', models.CharField(max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('host_name', models.CharField(max_length=30)),
                ('irdac_ip', models.GenericIPAddressField()),
                ('serial_number', models.CharField(max_length=30)),
                ('amc_end_date', models.DateField()),
                ('location', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=100)),
                ('cloud_purpose', models.CharField(max_length=50)),
            ],
        ),
    ]
