# Generated by Django 4.0.3 on 2022-12-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_physicalserverdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalServerCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_IP', models.GenericIPAddressField()),
                ('Host_name', models.CharField(max_length=20)),
                ('Total_VM', models.IntegerField()),
                ('Total_RAM', models.IntegerField()),
                ('Used_RAM', models.IntegerField()),
                ('Available_RAM', models.IntegerField()),
                ('Total_vCPU', models.IntegerField()),
                ('Used_vCPU', models.IntegerField()),
                ('Available_vCPU', models.IntegerField()),
                ('Total_local_storage', models.IntegerField()),
                ('Used_local_storage', models.IntegerField()),
                ('Available_local_storage', models.IntegerField()),
                ('Remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
