# Generated by Django 4.0.3 on 2022-12-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_physicalservercapacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LUN_ID', models.IntegerField()),
                ('Mounted_to_server_IP', models.GenericIPAddressField()),
                ('Mount_point', models.CharField(max_length=30)),
                ('Total_capacity', models.FloatField()),
                ('Used', models.FloatField()),
                ('Available', models.FloatField()),
                ('Remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
