# Generated by Django 4.0.3 on 2022-12-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_vminventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_ID', models.CharField(max_length=30)),
                ('Department_name', models.CharField(max_length=30)),
                ('Application_URL', models.URLField()),
                ('External_server_linked_to_the_application', models.CharField(choices=[('Payment gateway', 'Payment gateway'), ('SMS', 'SMS'), ('Email services', 'Email services')], max_length=30)),
                ('SSL_expiry', models.DateField()),
                ('SSL_Vendor', models.CharField(max_length=30)),
                ('APP_VM_ID', models.CharField(max_length=30, null=True)),
                ('DB_VM_ID', models.CharField(max_length=30, null=True)),
                ('Public_IP', models.GenericIPAddressField()),
                ('Live_Date', models.DateField()),
                ('Contact_detail_id', models.IntegerField()),
                ('Remarks', models.CharField(max_length=100)),
                ('Current_status', models.CharField(max_length=30)),
            ],
        ),
    ]
