# Generated by Django 4.0.3 on 2022-12-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0010_applicationinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetailsInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_ID', models.IntegerField()),
                ('Department_ID', models.IntegerField()),
                ('Application_ID', models.IntegerField()),
                ('Department_Name', models.CharField(max_length=30)),
                ('Department_mail', models.EmailField(max_length=254)),
                ('Department_phone_number', models.IntegerField()),
                ('Developer_Name', models.CharField(max_length=30)),
                ('Developer_mail', models.EmailField(max_length=254)),
                ('Developer_phone_number', models.IntegerField()),
                ('Remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
